repository:
  default_branch: main
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: true
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        checks:
          - Python Tests
          - Run Tests
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
